on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: jhale/fenicsx-error-estimation:debug
    name: CI
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          python3 -m pip -v install .
      - name: Run demos 
        run: |
          cd demo
          python3 -m pytest -v
